substitutions:
  uart_rx_pin: 3
  uart_tx_pin: 1

esphome:
  name: ${name}
  friendly_name: ${friendlyName}
  platformio_options:
    board_build.flash_mode: dio

esp32:
  board: esp32dev
  framework:
    type: esp-idf
    version: recommended
    # Custom sdkconfig options
    sdkconfig_options:
      COMPILER_OPTIMIZATION_SIZE: y
      CONFIG_FREERTOS_USE_TRACE_FACILITY: y
      CONFIG_FREERTOS_GENERATE_RUN_TIME_STATS: y
      CONFIG_FREERTOS_USE_STATS_FORMATTING_FUNCTIONS: y

uart:
  id: uart_ecodan
  rx_pin:
    number: GPIO${uart_rx_pin}
    mode:
      input: true
      pullup: true
  tx_pin:
    number: GPIO${uart_tx_pin}
    mode:
      output: true
  baud_rate: 2400
  parity: EVEN
  stop_bits: 1
  debug:
    direction: BOTH
    dummy_receiver: false
    after:
      delimiter: "\n"
    sequence:
      - lambda: UARTDebug::log_hex(direction, bytes, ' ');

sensor:
  - platform: internal_temperature
    name: ${internal_esp_temperature}
    entity_category: diagnostic
    unit_of_measurement: "°C"
    device_class: temperature
